<?php

return [
    'file-manager' => '檔案管理',
    'search' => '搜尋',
    'delete' => '刪除',
    'move' => '移動',
    'archive' => '壓縮',
    'unarchive' => '解壓縮',
    'create-directory' => '創建資料夾',
    'upload' => '上傳',
    'new-file' => '創建新檔案',
    'rename' => '重新命名',
    'permissions' => '權限',
    'copy' => '複製',
    'download' => '下載',
    'update' => '更新',
    'file-mode' => '檔案模式',
    'you-cant-recover' => '刪除 ',
    'once-deleted' => ' 之後，您將無法恢復檔案內容',
    'delete-files' => '刪除檔案',
    'are-you-sure' => '您確定要刪除嗎',
    'this-is-permanent-action' => '這是永久性操作，檔案將無法恢復',
    'name' => '名稱',
    'size' => '大小',
    'date' => '日期',
    'home' => 'home',
    'container' => 'container',
    'is-empty' => '此資料夾是空的',
    'is-limited' => '此資料夾有太多檔案，瀏覽器無法顯示，瀏覽器最多只能顯示 250 個檔案，請使用 SFTP 查看',
    'are-upload-click-to-view' => '檔案正在上傳，點按以查看',
    'cancel-uploads' => '取消上傳',
    'cancel' => '取消',
    'close' => '關閉',
    'create' => '創建',
    'file-name' => '檔案名稱',
    'file-name-description' => '輸入要創建的檔案名稱',
    'directory-will-be-as' => '此資料夾會被創建在 ',
    'rename-description' => '輸入此檔案 / 資料夾的新名稱，可使用相對於此資料夾的相對路徑',
    'new-location' => '新的位置',
    'drag-and-drop' => '把檔案拉到這裡來上傳',

    'edit' => [
        'youre-editing' => '您正在編輯 ',
        'will-be-exluded' => '，所有在此列出的檔案 / 資料夾都不會被備份，使用 "*" 可使用通用符號',
        'you-can-negate' => '您可以在前面加上 "!" 來取消此規則',
        'save-content' => '儲存檔案',
        'create-file' => '創建檔案',
    ],
];
