<?php 

return [
    'schedules' => '排程',
    'manage-schedules' => '管理排程',
    'create-schedule' => '創建排程',
    'name' => '名稱',
    'last-run-at' => '上次執行: ',
    'next-run-at' => '下次執行: ',
    'status' => '狀態',
    'active' => '啟用',
    'inactive' => '停用',
    'processing' => '執行中',
    'manage-schedule' => '管理排程',
    'new-task' => '新工作',
    'run-now' => '現在執行',
    'editBtn' => '編輯',
    'n/a' => 'N/A',
    'never' => '永不',

    'no-schedules' => '這伺服器沒有設定排程',
    'ignore-files-folders' => '跳過檔案/資料夾',
    'continues-on-failure' => '於失敗時繼續執行',
    'later' => '稍後',

    'minute' => '分鐘',
    'hour' => '小時',
    'day' => '天',
    'week' => '禮拜',
    'day-of-month' => '一個月中的哪一天',
    'month' => '月',
    'day-of-week' => '一個禮拜中的哪一天',

    'deleteTask' => [
        'title' => '確認刪除工作',
        'description' => '你確定要刪除這個工作嗎，這個操作無法恢復',
        'delete' => '刪除工作'
    ],
    'delete' => [
        'title' => '刪除排程',
        'description' => '所有工作都會被移除，執行中的工作將會被停止',
        'delete' => '刪除'
    ],
    'edit' => [
        'title-1' => '編輯排程',
        'title-2' => '創建排程',

        'description' => '排程系統支援使用 Cronjob 格式來決定排程應該在什麼時候執行，使用上方的格子來決定排程應該在何時執行',
        
        'name' => '排程名稱',
        'name-description' => '打你看得懂的東西就好',
        'cheatsheet' => '顯示快速參考指令表',
        'cheatsheet-description' => '顯示一些 cron cheatsheet 的範例',
        'online-when-online' => '僅在伺服器在線上時執行',
        'online-when-online-description' => '僅會在伺服器狀態為 執行中 的時候執行此排程',
        'enabled' => '排程已啟用',
        'enabled-description' => '排程將會在啟用的時候自動執行',

        'save-changes' => '儲存變更',
    ],
    'cheatsheet' => [
        'example' => '範例',
        'every-5-minutes' => '每 5 分鐘',
        'every-hour' => '每個小時',
        'hour-range' => '小時範圍',
        'once-a-day' => '一天一次',
        'every-monday' => '每個禮拜一',
        'special-characters' => '特殊符號',
        'any-value' => '任何值',
        'value-list-separator' => '值列表分隔符號',
        'range-values' => '範圍符號',
        'step-values' => '步驟值',
    ],
    'task' => [
        'message' => '備份任務無法在伺服器可用備份數量為 0 時創建',
        'edit-task' => '編輯任務',
        'save-changes' => '儲存變更',
        'create-task' => '創建任務',
        'action' => '動作',
        'send-command' => '傳送指令',
        'send-power-action' => '傳送電源操作',
        'create-backup' => '創建備份',
        'offset' => '時間偏移 (以秒記)',
        'offset-description' => '在前一個任務執行後值行此任務之前等待的時間。如果這是排程中的第一個任務，則不會套用此設定',
        'payload' => '負載',
        'ignored-files' => '跳過的檔案',
        'ignored-files-description' => '選填。在這裡輸入的檔案/資料夾將會被排除在備份任務創建的備份之外，預設將會使用/home/container/.pteroignore檔案內的排除列表。如果到了備份上限，最舊的備份將會被刪除',
        'start-server' => '啟動伺服器',
        'stop-server' => '停止伺服器',
        'restart-server' => '重啟伺服器',
        'kill-server' => '強制停止伺服器',
        'continue-on-failure' => '於失敗時繼續執行',
        'continue-on-failure-description' => '此任務失敗時，後面的任務將會繼續執行',
    ],
];
