<?php

return [
    'online' => '在線',
    'offline' => '離線',
    'starting' => '啟動中',
    'stopping' => '停止中',
    'suspended' => '被暫停',
    'connection-error' => '連線錯誤',
    'transferring' => '轉移中',
    'installing' => '安裝中',
    'restoring-backup' => '恢復備份中',
    'unavailable' => '不可用',
    'status' => '狀態',
    'CPU' => '處理器',
    'memory' => '記憶體',
    'disk' => '儲存空間',
    'unlimited' => '無限',
    'start' => '啟動',
    'restart' => '重啟',
    'stop' => '停止',
    'kill' => '強關',
    'forcibly-stop-process' => '強制停止程序',
    'continue' => '繼續',
    'forcibly-stopping-alert' => '強制停止伺服器可能會導致資料遺失，後果自負。',
    'cpu-usage' => '處理器使用率',
    'memory-usage' => '記憶體使用率',
    'disk-usage' => '儲存空間使用率',
    'inbound-outbound' => '下載 / 上傳',
    'low-resources' => '資源不足',
    'low-resources-desc' => '你的伺服器資源不足，嘗試升級伺服器以獲得更多資源。',
    'upgrade-server' => '升級伺服器',
    'cancel' => '取消',
    'copied-text' => '已複製 {{text}} 到剪貼簿。',
    'showing' => '顯示',
    'to' => '到',
    'of' => '在',
    'results' => '結果。',
];